### ISSUE TITLE
Získavanie odznakov

### ISSUE THREAD

**Issue by StanlieK** [AskalotCQA/askalot#2]
V systéme Askalot som došiel na chybu, kedy sa počíta kažý Vote, keď niekomu dám Vote up a zruším ho, a znovu dám Vote up, tak sa to počíta za dva Votes, pričom by to podľa mňa bolo dobré ošetriť.

**Comment by adrianhuna** [comment]
Prepáč, že ti na toto nikto neodpovedal. Máš pravdu, bola tam chyba a myslím, že bola vďaka tvojmu reportu opravená. Celkovo odznaky boli súčasťou jednej bakalárskej práce, takže určite super, že si nás na toto upozoril :)
