### ISSUE TITLE
Admin rights only checked on account creation

### ISSUE THREAD

**Issue by QuCryptoX** [AskalotCQA/askalot#4]
We upgraded (on edX) the roles of several of our staff members to admin. However, askalot did not update their roles accordingly and they cannot edit posts or evaluate questions. 

It be great if askalot did this automatically, but otherwise, is there any way of changing the rights of users directly on askalot?

Thanks in advance!

**Comment by adrianhuna** [comment]
Hello. You are right. Askalot currently only stores user role upon registering user, so the roles are not updated if you change them later in edX administration. We will update this behavior soon and deploy new version (probably) before Monday.

**Comment by adrianhuna** [comment]
We deployed new version containing a fix for this issue so everything should be working according to your needs.

**Comment by QuCryptoX** [comment]
Thanks a lot for the quick reply! Unfortunately it is not working yet for us, for instance user kdgoodenough is and admin on edX but not yet on askalot.

**Comment by adrianhuna** [comment]
In order for the roles to be updated, it's required to visit Askalot in unit. Can you confirm he did so?

**Comment by QuCryptoX** [comment]
To be honest, I am not sure what is unit, do you mean edx studio?

**Comment by adrianhuna** [comment]
By unit, I mean a part of your course that contains Askalot component besides some learning materials.

For your case, that would be e.g. https://courses.edx.org/courses/course-v1:CaltechDelftX+QuCryptox+3T2016/courseware/f286a8dd5fd2436caaa190a234d5a690/f90d22edc8ae4872bae4027497e6b159/

Additionally, feel free to write us at askalot@fiit.stuba.sk if you would prefer more private conversation.

**Comment by KDGoodenough** [comment]
Hii Adrian, I visited the unit page but I do not yet have admin rights, unfortunately.

**Comment by isrba** [comment]
@KDGoodenough, we just want to make sure - when you visit your course, as an admin user, you have a possibility to see the course as "Staff", "Student" or "Specific student" (this option is available right above the main course menu). Please, could you let us know which option do you use?

We suppose that you may have set it to "Student" or "Specific student" and thus you appear to Askalot as a student and not as an admin. And therefore, Askalot cannot, of course, recognize your edX role properly.

If this is not your case, we will do our best to find a solution. Thank you very much for your patience.

**Comment by KDGoodenough** [comment]
@isrba The option was set to student (because I'm also doing beta testing). I set it now to staff, but nothing has changed yet. I also revisited the unit page again.

**Comment by isrba** [comment]
@KDGoodenough, if I am right, I suppose that you have just found a bug in edX platform. You do not have to just change your role to "Staff" but also you need to logout and login again.
- You are assigned with administrator role in edX studio. 
- When you login, you have administrator role - it is ok.
- You can change your role temporally to a student role in the above mentioned select box.
- When you select staff role back, you should have your default administrator role again, right? But actually, edX assigns you with ordinary staff (teaching assistant) role.

That is why Askalot cannot detect that you are administrator now. Please, could you try to set staff role in edX, logout and login again. And let us know, we will check logs and we will see what edX will send us as your role.

Thank you for your help.

**Comment by KDGoodenough** [comment]
Logging out and back in again seemed to do the trick :) Thank you very much!

**Comment by isrba** [comment]
@KDGoodenough, we can confirm that your role in Askalot has been changed.

To conclude for future reference - to reflect the change of role in edX, it is necessary to:

1. Set user's temporary role in edX to "Staff" and not "Student" or "Specific student". Otherwise, edX naturally send a student role and thus we cannot detect the change.
2. With role set to "Staff", it is necessary to logout and login again due to a bug (or maybe very weird feature) in edX.
3. Visit any unit with Askalot. The role in Askalot will be reflected automatically.

@KDGoodenough, one more time thank you for solving this issue with us. As you can see, the implementation of your change request was implemented correctly from the very beginning, however, we did not realize that you can have different temporary role and moreover, we did not expect that bug in edX at all.
